require("./config/port")
const cors = require('cors')
const bodyParser = require('body-parser')
const express = require('express')
const app = express()
const user = require("./view/user")
const mercado = require("./view/mercado")
const insumo = require("./view/insumo")
const lote = require("./view/lote")
const peso = require("./view/peso")
const notification = require("./view/notification")
const residuo = require("./view/residuo")
const fase = require("./view/fase")
const actividad = require("./view/actividad")
const entrada = require("./view/entrada")

app.use(bodyParser.urlencoded({ extended: false }))
app.use(bodyParser.json())
app.use(cors())

/** APIS **/
app.use(user)
app.use(mercado)
app.use(insumo)
app.use(lote)
app.use(peso)
app.use(notification)
app.use(residuo)
app.use(fase)
app.use(actividad)
app.use(entrada)
app.listen(process.env.PORT,()=>{
    console.log("SERVER LISTEN "+process.env.PORT)
})